### ISSUE TITLE
Add `vX` tags

### ISSUE THREAD

**Issue by alexesprit** [richardsimko/update-tag#4]
I suggest to add `vX` tags, where `X` is a major version of the action. This allows to use the action safer:
```
uses: richardsimko/update-tag@v1
```
Using `master` reference is not recommended, as it could contain non-compatible changes.

The `vX` tag should point on the latest `vX.x.x` release (e.g. `v1` -> `v1.x.x`).

This could be done automatically with this very action. The workflow file to update a reference to a latest release.

```yml
# update-tag.yml

name: Update version reference
on:
  release:
    types: [edited, published]
jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
      - name: Extract major version from tag
        run: |
          FULL_VERSION=${GITHUB_REF##*/}
          MAJOR_VERSION=$(echo "${FULL_VERSION%.*.*}")
          echo "::set-env name=TAG_NAME::${MAJOR_VERSION}"
      - name: Update reference to latest version
        uses: ./
        with:
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This way is recommended in the documentation: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md.
